### ISSUE TITLE
Linking lines are broken after page resize

### ISSUE THREAD

**Issue by bogomya** [antonioru/beautiful-react-diagrams#4]
![image](https://user-images.githubusercontent.com/7804416/84664643-82b97900-af27-11ea-9be1-2fbdb70a087a.png)

**Comment by antonioru** [comment]
Thank you for pointing this out @bogomya 
I'll have a look at it as soon as possible

**Comment by alexratmanpl** [comment]
Hi @antonioru 
That's very annoying bug indeed - when working with more nodes, especially when you have to place them inside a scrollable 'div', there's no way to link and manipulate them correctly - I would be very happy to use your tool in my project but because of that bug it's not possible.
You probably could fix that very easily by modifying `useEffect` function in `DiagramCanvas.js ` and let it refresh the current position of canvas on each update, something like:
`useEffect(() => calculateBBox(canvasRef.current));`
In that case I suppose you may consider removing `useWindowScroll` hook as well.
Btw. great job, simple tool, clean code - it was kind of pleasure to search for a possible solution of fixing that bug. Congrats!

**Comment by antonioru** [comment]
@alexratmanpl @bogomya 

Thank you for pointing this out and supporting the project, I can't wait to work again on it as I really love this library. 
I hope to do it as soon as possible so I can fix this precise bug and bring new improvements. 
Unfortunately at the moment I am quite busy with work and personal life, but I would love to have some contributions. 
Please feel free to open a PR 

thank you

**Comment by volkan-a** [comment]
Hi @antonioru, is there any progress? I really would like to use on my project.

**Comment by antonioru** [comment]
> Hi @antonioru, is there any progress? I really would like to use on my project.

Hi @volkan-a 
thank you for your concern, as mentioned in the previous comment: at the moment I am quite busy with work and personal life, but I would love to have some contributions.
If you feel like you need some improvements please feel free to open a PR :)

**Comment by volkan-a** [comment]
I think @alexratmanpl's suggestion works.

Just change line 31 in DiagramCanvas.js as:

` useEffect(() => calculateBBox(canvasRef.current), [canvasRef.current, props]);`

then it works. But I have no idea if that affects performance.

**Comment by antonioru** [comment]
@volkan-a 
This is an open source software, meaning everyone is titled to contribute. 
If you want, make the change by yourself, test it, make sure it does not break anything and does not affect performances then open a PR I will be very happy to look at.

**Comment by antonioru** [comment]
@volkan-a @bogomya 
Apparently this bugs appears on Firefox only, can you confirm it?

**Comment by antonioru** [comment]
@volkan-a @bogomya 

Ok I think I solved the bug in the last published version: `0.2.0` 

Please let me know if it works for you as well...
